### ISSUE TITLE
@bind ed MultiSelect UI desyncs with the state

### ISSUE THREAD

**Issue by MasonProtter** [JuliaPluto/PlutoUI.jl#104]
Hey, when I use a `PlutoUI.MultiSelect` in a notebook in both FireFox and Chrome, it's only allowing me to select one element from the list. If I click on a second element, the first one gets de-selected.

Am I doing something wrong here? Is this a bug? 

https://user-images.githubusercontent.com/29157027/118054765-1831d880-b344-11eb-95ef-f46a6b1381b4.mp4

**Comment by pankgeorg** [comment]
Can you try with control + click?
If that works, please close this issue!

You can also use the `MultiCheckBox(["Potato", "Something", "Else"])` that doesn't need control + click

**Comment by MasonProtter** [comment]
Oh, I didn't know this required ctrl-click, maybe that should be mentioned in the docstring. Using ctrl-click I can select two elements at a time but either ctrl + click or just click on the third element ends up erasing the previous two.

**Comment by pankgeorg** [comment]
It's mentioned in the [HTML specification](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/select#selecting_multiple_options), no need for extra docstrings.

Indeed there seems to be some kind of issue, please use a MultiCheckBox for now, thanks!

**Comment by MasonProtter** [comment]
:shrug: The docstring and sample notebooks seem needlessly unhelpful in this regard. They mention that we can read the Mozilla docs, but the link to the mozilla docs are a rather technical page about how to create multiselect fields in HTML, with usage info buried down below. 

My understanding was that the entire point of PlutoUI.jl was that it was made so that users didn't have to know how to write HTML

**Comment by pankgeorg** [comment]
> 🤷 The docstring and sample notebooks seem needlessly unhelpful in this regard. 

I'm sorry you didn't find what you needed. PlutoUI does not implement custom HTML elements when there exist. Such a documentation

>They mention that we can read the Mozilla docs, but the link to the mozilla docs are a rather technical page about how to create multiselect fields in HTML, with usage info buried down below.

I will kindly disagree, Mozilla docs are pretty nice.

> My understanding was that the entire point of PlutoUI.jl was that it was made so that users didn't have to know how to write HTML

The issue you have written 2.5 comments about is about HTML **usage** not **authoring**. As I understand it, teaching HTML _usage_ is out of PlutoUI scope.

You can use one of the two options you have available from this package. We'll investigate the MultiSelect functionality issue when we have some time.

Thank you for your time.
