### ISSUE TITLE
On the behavior of MultiCheckBox when there are duplicate keys/values

### ISSUE THREAD

**Issue by jin-park** [JuliaPluto/PlutoUI.jl#106]
I like most parts about `MultiCheckbox` but I think there are some "quirks" with `MultiCheckBox` that need to be sorted out.

### MultiCheckBox with duplicate keys

Here's a use case of `MultiCheckBox` (it's the example in the docstring plus "🥕" => "🦈")

#### Initialization

<img width="709" alt="Screen Shot 2021-05-18 at 12 44 40 AM" src="https://user-images.githubusercontent.com/61643387/118520992-86780000-b775-11eb-90d5-1eaf796fb04a.png">

#### Now with the shark unselected

<img width="709" alt="Screen Shot 2021-05-18 at 12 44 55 AM" src="https://user-images.githubusercontent.com/61643387/118520719-40bb3780-b775-11eb-84e4-e55a9422eca8.png">

#### Shark selected again

<img width="708" alt="Screen Shot 2021-05-18 at 12 45 18 AM" src="https://user-images.githubusercontent.com/61643387/118520618-2aad7700-b775-11eb-820e-067fc66cdffd.png">
 
As you can see the value of `snacks` changes. Maybe the bind value returned should only contain unique elements, maybe it could contain duplicate elements, or maybe even the user could decide; either way I think it needs to have some consistent behavior.

#### MultiCheckBox with duplicate values

Now this is less of a quirk and more of an opinion of mine. That being said, I think this

<img width="708" alt="Screen Shot 2021-05-18 at 1 19 23 AM" src="https://user-images.githubusercontent.com/61643387/118522919-90026780-b777-11eb-843d-4278e64a30d5.png">

should not be allowed. Something irks me about two identically looking checkboxes doing different things (i.e. one carrot adding a rabbit emoji to the bind value and the other adding a shark emoji). I don't know, maybe it's just me, but I'd like to know what the Pluto devs think. 

P.S. It's been a while since I've used Pluto but I really love how PlutoUI's turning out! I'll have to try out all the wonderful widgets! ❤️

**Comment by fonsp** [comment]
Thanks! Fixed now :)

https://user-images.githubusercontent.com/6933510/146605864-befa4e9b-5d1d-4338-912a-edcdb352da5c.mov
