### ISSUE TITLE
TOC covers notebook content

### ISSUE THREAD

**Issue by StefanKarpinski** [JuliaPluto/PlutoUI.jl#111]
Looking at https://glenhertz.github.io/dft/dft.jl.html (cc @glenhertz), I see this:

<img width="1229" alt="Screen Shot 2021-06-04 at 4 21 47 PM" src="https://user-images.githubusercontent.com/153596/120858684-2349e400-c551-11eb-84cd-3604b9719669.png">

If I make the window *really* wide it eventually doesn't cover it, but it's really absurdly wide and I don't even have enough space on my laptop screen to make it that wide. Same issue in both Safari and Chrome.

**Comment by GlenHertz** [comment]
Can the TOC and main column be percentages of the total width?  It seems that the left margin is fixed (and blank) which isn't optimal in this case for usage of screen space.

**Comment by pfitzseb** [comment]
Maybe it'd make sense to inject the TOC further up in the dom (as a sibling to `pluto-notebook`); styling this better should be almost trivial then. Much less of a clean solution than just re-using a floating cell output though.

**Comment by fonsp** [comment]
Thanks! The problem here is that the notebook is centered in "print view" (used in static exports), and pushed to the left in "edit view". The ToC was only designed for the latter

**Comment by disberd** [comment]
A very _hacky_ solution for anyone who finds the need to share static notebooks and keep the ToC without disrupting normal content is to add a cell with the following code:

```julia
html"""
<style>

#launch_binder {
	display: none;
}

body.disable_ui main {
		max-width : 95%;
	}

@media screen and (min-width: 1081px) {
	body.disable_ui main {
		margin-left : 10px;
		max-width : 72%;
		align-self: flex-start;
	}
}
</style>
"""
```

This hides the Edit or Run in binder button and resize the `main` tag to basically fit most of the visible browser space.
The width of 1081 is the same one that triggers the ToC to disappear from the side.

Here how it looks on the static export:

![image](https://user-images.githubusercontent.com/12846528/123804566-9e52b000-d8ed-11eb-9a7e-882f2466d85b.png)
