### ISSUE TITLE
MultiCheckBox creates a binding equal to Nothing if default is specified

### ISSUE THREAD

**Issue by tobi-lipede-oodle** [JuliaPluto/PlutoUI.jl#117]
I was just playing around with `MultiCheckBox` and noticed that when specifying a default, the bound value gets set to `nothing`. E.g. a MWE from the example docs:

```julia
# Cell 1
@bind snacks MultiCheckBox(["🥕" => "🐰", "🐟" => "🐱", "🍌" => "🐵"]; default=["🥕", "🍌"])

# Cell 2 
snacks === nothing  # true
```
If I manually check or uncheck any of the boxes once this goes back to normal.

**Comment by tobi-lipede-oodle** [comment]
On further investigation, I think `MultiCheckBox` binds twice for some reason - I do notice child cells updating twice when I click on a checkbox.

**Comment by rapus95** [comment]
even worse that than I encountered a situation where runing the defining cell once creates the correct selection and binding. But on clicking ANYWHERE it suddenly triggers an update placing `nothing` into the bound variable.

**Comment by fonsp** [comment]
Closed in https://github.com/JuliaPluto/PlutoUI.jl/commit/bb2a694cf76d35b5161b26edb7714b1e497c14f9
