### ISSUE TITLE
RangeSlider breaks inside of markdown `$()` and returns nothing

### ISSUE THREAD

**Issue by FelixBenning** [JuliaPluto/PlutoUI.jl#119]
![image](https://user-images.githubusercontent.com/29106652/126071417-5c1c7124-c0ef-4c16-97b7-b99e0d64e5aa.png)

```julia
md"Test Range slider
$(@bind test RangeSlider(0:2, left=1, right=2))
"
```

**Comment by fonsp** [comment]
Fixed by #160 

![Schermafbeelding 2021-12-19 om 00 08 28](https://user-images.githubusercontent.com/6933510/146657828-36c9db5d-2fe9-41b7-b4e7-958eb0a86cf7.png)
