### ISSUE TITLE
Missing documentation on non-builtins

### ISSUE THREAD

**Issue by ultradian** [JuliaPluto/PlutoUI.jl#121]
The documentation at https://juliahub.com/docs/PlutoUI/ has docstrings for all the Builtins, but not for other components like `Clock`, `MulticheckBox`, or `TableOfContents`.   

I don't know enough about using `Documenter` to help with this yet, but this is a really cool package that deserves good docs to get more people involved.

**Comment by fonsp** [comment]
Thanks! Linked to #142
