### ISSUE TITLE
PlutoUI.NumberField changes value whenever you hit backspace or delete to change its value.

### ISSUE THREAD

**Issue by ghralima** [JuliaPluto/PlutoUI.jl#127]
When using PlutoUI.NumberField, the variable changes it's value whenever you hit backspace, delete or number keys. Maybe a better behaviour for NumberFiled should be to accept the change in the variable only after the enter key is pressed, or an option could be added when calling it to enable this behaviour.

**Comment by icweaver** [comment]
This sounds similar to #177. Would wrapping in `PlutoUI.confirm` be alright?

```julia
using PlutoUI

@bind x confirm(NumberField(1:10))
```
![Screenshot from 2022-01-04 17-05-11](https://user-images.githubusercontent.com/25312320/148130094-5d127bf9-334f-4b3f-8d12-5323648a68c5.png)

**Comment by ghralima** [comment]
Yes, I think that should fix this behaviour! Thanks!
