### ISSUE TITLE
Docstrings for builtins have disappeared from the website

### ISSUE THREAD

**Issue by stillyslalom** [JuliaPluto/PlutoUI.jl#142]
Docs for builtins have disappeared. Compare: 
https://docs.juliahub.com/PlutoUI/abXFp/0.7.13/autodocs/
https://docs.juliahub.com/PlutoUI/abXFp/0.7.14/autodocs/

Introduced here: https://github.com/fonsp/PlutoUI.jl/commit/7bea045af67d7e5f97705ac5e2d6a735e80797de#diff-8b0c48eb5f96f119efd3a842f2340cdfb5afbd1dff673a905bcafeebf30f0898R10-R12

Looks like Documenter.jl doesn't like Reexport.jl.

**Comment by fonsp** [comment]
Also #158
