### ISSUE TITLE
MultiCheckBox values nothing even with default values

### ISSUE THREAD

**Issue by lucasresenderc** [JuliaPluto/PlutoUI.jl#143]
The following image shows an unexpected behavior for the MultiCheckBox:
![image](https://user-images.githubusercontent.com/24375125/137132811-db5f8831-baf1-46fb-8061-43095623456b.png)

Thanks in advance.

**Comment by juliohm** [comment]
Appreciate if anyone from the Pluto team can take a look at this. 🙏🏽
