### ISSUE TITLE
Namespace clash with Makie

### ISSUE THREAD

**Issue by laserkelvin** [JuliaPluto/PlutoUI.jl#144]
I looked into the issues and didn't see this, but apologies if this is already known:

On the latest version of Pluto/PlutoUI, importing GLMakie raises a warning in the terminal output:

```
From worker 2:    WARNING: both GLMakie and PlutoUI export "Slider"; uses of it in module workspace25 must be qualified
```

...and unless you explicitly call `PlutoUI.Slider`, `Slider` is not actually imported. Not a huge problem since you can just be explicit, but I wasn't sure if others were aware of this.

**Comment by fonsp** [comment]
Thanks! You can subscribe to https://github.com/fonsp/Pluto.jl/issues/890
