### ISSUE TITLE
Slider doesn't update the value in the same cell

### ISSUE THREAD

**Issue by VarLad** [JuliaPluto/PlutoUI.jl#145]
![Screenshot from 2021-10-20 01-29-45](https://user-images.githubusercontent.com/51269425/137981786-4c32fd57-c54a-4a26-b0a6-63488a1cd3da.png)

**Comment by dralletje** [comment]
That's right.
The reason is that re-running the cell would generate new html for the slider, thus forcing re-render, which would make the slider lose focus. For now `@bind`'s will have to go in separate cells to where their result is used.
