### ISSUE TITLE
PlutoUI's Select type has the order of the pairs wrong

### ISSUE THREAD

**Issue by KronosTheLate** [JuliaPluto/PlutoUI.jl#159]
Copy of [this](https://discourse.julialang.org/t/plutouis-select-type-has-the-order-of-the-pairs-wrong/71082) discourse post:

The `Select` type allows the user to create down-down menus with the `@bind` macro. Awesome feature.
The current behaviour is
![image|690x126, 75%](https://user-images.githubusercontent.com/61620837/142827464-49deeb0c-550c-4ada-83c9-d12c334891d3.png)

The docs for `Select` look like this:
![image](https://user-images.githubusercontent.com/61620837/142827514-54969e3e-bd14-4754-b72e-9bbcc7f96c25.png)

So in the language of the docs, `"1"` is the key, and `"one"` is the value. key=>value is consistent with `Dict`, and feels right. But it feels to me as the entry visible in the drop-down is the key, used to index to the right value. The key has a name that makes sense, but the value is what you are really interested in. But currently, the opposite is the case.

Additionally, `keys` are of type string, but `values` are of type any. I want variables to have any type, but drop-down entries to have type `String`. The other way around, which is currently the case, makes no sense:
![image](https://user-images.githubusercontent.com/61620837/142827540-a3e1e794-000c-42a5-bc8f-ffe88dccca76.png)

Could I be right in saying that the first value, the key of type `String`, should be shown in the drop-down? And that the second value, the value of type `Any`, should be bound to the variable? It makes more sense, and is a lot more powerful.

**Comment by fonsp** [comment]
Thanks for pointing this out, I keep getting confused about this myself!

It looks like I allowed `Any` on the wrong side in #148 , let me fix this and clear up the docs!

**Comment by KronosTheLate** [comment]
Great! Do you have any thought on my feeling that it would be more logical to have the first item in the pair be the displayed one, and the second to bind to the variable? It is so massivly breaking that it is probably not worth it, but I am curius about your thoughts.

**Comment by fonsp** [comment]
Right! Like you say, it's too breaking to change now, but I also get confused sometimes. I think both make sense

**Comment by KronosTheLate** [comment]
Yhea, there is not a clear answer, and I can see that both make some sense. I guess the best solution then is to make the order _really clear_ in the documentation ^_^
