### ISSUE TITLE
PlutoUI v0.7.22 breaks DataFrames.combine

### ISSUE THREAD

**Issue by MrHenning** [JuliaPluto/PlutoUI.jl#166]
### Expected:
![image](https://user-images.githubusercontent.com/5331081/145790452-838f5feb-56e9-412a-9a38-719d5c5cdc2c.png)

### with PlutoUI `v0.7.22`:
![image](https://user-images.githubusercontent.com/5331081/145790524-591e0d05-4caf-46e7-bb0c-323975d9ecb7.png)

using
```
PlutoUI v0.7.22
DataFrames v1.3.0
```

The notebook can be fixed by adding `using DataFrames: combine`, but maybe it'd be nice if it would work without?

Thanks for you awesome work :)

**Comment by fonsp** [comment]
☹️

**Comment by fonsp** [comment]
Since this feature wasn't heavily advertised yet, I think it's fairly safe to remove the export and tag a release today. People should use it with `PlutoUI.combine`
