### ISSUE TITLE
TimeField and DateField that return a `Dates.Time` and `Dates.Date`

### ISSUE THREAD

**Issue by fonsp** [JuliaPluto/PlutoUI.jl#169]
We already have a `TimeField` widget that returns the selected time as a *String* (boooo), which was the only possibility last year.

Since #148 , it is possible to **transform** a value before assigning it to the bound julia variable. For example, take a look at https://github.com/JuliaPluto/PlutoUI.jl/pull/168

This means that we can create a new `TimeField` and `DateField` that return the Julia date and time fields directly!

Let's call it `TimePicker` and `DatePicker` to avoid breaking the existing functions.

**Comment by icweaver** [comment]
Okie doke, just opened!
