### ISSUE TITLE
Slider displays something but variable contains something else

### ISSUE THREAD

**Issue by juliohm** [JuliaPluto/PlutoUI.jl#175]
![image](https://user-images.githubusercontent.com/3345261/146656764-4530f2fc-4134-409e-96bc-526254e04cac.png)

Here is the code to reproduce:

```julia
using PlutoUI

@bind x PlutoUI.Slider(1000.0:10.0:4000.0, default=2365.67, show_value=true)

x
```

**Comment by icweaver** [comment]
Hey Júlio! I think `Slider` just falls back to the number that's in the "middle" if the original default value we specify doesn't live in our range once it's materialized:

```julia
using PlutoUI

@bind x PlutoUI.Slider([1, 10, 42, 1_000], default=7)

x
```

![Screenshot from 2022-01-04 17-24-21](https://user-images.githubusercontent.com/25312320/148132121-1dc1520f-f14d-49da-bb0f-2351f8a588d3.png)

which seems reasonable to me. So changing the default value in your example to something like `2360.0` should do the trick then I think

**Comment by juliohm** [comment]
Hi Ian! I think this is a bit counter intuitive. A more natural behavior would be to show an error saying that the default is not in the range, or return the closest value in the range as the default. Right now this value is being silently passed forward, which causes more serious issues downstream.

**Comment by juliohm** [comment]
Alternatively, make this default an initial value ignoring the specified range. The keyword default=1.0 means init=1.0, right?

**Comment by icweaver** [comment]
Yea, I can definitely see users potentially getting tripped up by this. I'm thinking now that trying to avoid as much mind-reading as possible might be the best way forward, so I really like your suggestion to just raise an error. I'm seeing now that this could also avoid potentially confusing outputs like these:

![Screenshot from 2022-01-04 18-01-29](https://user-images.githubusercontent.com/25312320/148135642-b1c39e27-d95a-4a93-acfa-6628b5e23ac5.png)

> The keyword default=1.0 means init=1.0, right?

Sorry, I'm not sure what you mean by this

**Comment by juliohm** [comment]
Sorry I tried to ask if the keyword default=1.0 has the meaning "initial
value is 1.0". Maybe the keyword could be renamed in a future breaking
release? Maybe Im asking it is just because I'm not a native speaker.
Default should be fine i guess.

**Comment by icweaver** [comment]
Ahh, gotcha, was just a misunderstanding on my end. I believe it does (or at least should if 1.0 is in the array formed from the range that's passed to it), so I agree that the name is fine too. If no default is given, then it just falls back to the first element of the array

**Comment by icweaver** [comment]
oop, found related discussion in #58
