### ISSUE TITLE
Introducing a delay on calculation of values associated to Slider

### ISSUE THREAD

**Issue by egonik-unlp** [JuliaPluto/PlutoUI.jl#177]
Is it possible to make sliders somehow pass on the value once the slider stops moving? I have somewhat heavy computations downstream of the slider, and would like to be able to only make them once the slider stops moving. 

thanks!

**Comment by pankgeorg** [comment]
Can you check if the `PlutoUI.confirm` function is what you need?
Take a look here: https://juliapluto.github.io/sample-notebook-previews/PlutoUI.jl.html

![image](https://user-images.githubusercontent.com/8681967/147605355-eda135bf-16d4-491b-9453-05231ce3fad5.png)

**Comment by egonik-unlp** [comment]
It really helps! I see only two problems with that particular implementation:

1. It's in english (the target audience are spanish speaking chemistry students)
2. I use multiple sliders, so it seems a bit cumbersome to have to confirm every change you decide to make (perhaps something along the lines of a single PlutoUI.Button would be better)

Thanks for your answer!

**Comment by icweaver** [comment]
Hey all, happy new year!

1. I think that's a great point, @egonik-unlp, and I think that would be great additional functionality to add
2. @pankgeorg and the rest of the Pluto wizards have been hard at work to make this a [reality](https://github.com/fonsp/Pluto.jl/discussions/923#discussioncomment-1860770)! Here's a quick example from the Live docs for `confirm` (I just took a few liberties with the mixing and matching of markdown and html + libraries used):

```julia
using PlutoUI
using MarkdownLiteral: @mdx

@bind speeds confirm(
    PlutoUI.combine() do Child
        @mdx("""
        ### Wind speeds
        <ul>
        $([
            @mdx("<li>$(name): $(Child(name, Slider(1:100)))")
            for name in ["North", "East", "South", "West"]
        ])
        </ul>
        """)
    end
)

speeds
```

![Screenshot from 2022-01-04 17-46-09](https://user-images.githubusercontent.com/25312320/148134259-2a44f512-fd04-4bb2-8106-36b8ec552d75.png)

**Comment by fonsp** [comment]
Let's discuss 1. in a new issue! https://github.com/JuliaPluto/PlutoUI.jl/issues/183

**Comment by fonsp** [comment]
I think the best answer to the original question is a *debounce*, see #69 , #105 , https://lodash.com/docs/4.17.15#debounce and https://css-tricks.com/debouncing-throttling-explained-examples/ for more info

**Comment by egonik-unlp** [comment]
Thank you all very much!
