### ISSUE TITLE
with_terminal() possibly stopped working with Pluto 0.17.6 

### ISSUE THREAD

**Issue by j-fu** [JuliaPluto/PlutoUI.jl#192]
Hi it seems that the new logging stuff interfers with `with_terminal()`. Not that I wouldn't prefer logging, but for backwards compatibility this could be a problem, see the notebook in   https://gist.github.com/j-fu/550df5a6bdb58350c43746d5e8ae453c .

**Comment by icweaver** [comment]
Looks to be working alright on `main` I think!

![Screenshot from 2022-01-21 13-13-33](https://user-images.githubusercontent.com/25312320/150578955-7676977a-fd99-4015-9858-aea8cd94d68e.png)

**Comment by j-fu** [comment]
Ah ok. I can confirm this. Thanks for the response!
