### ISSUE TITLE
Dark mode

### ISSUE THREAD

**Issue by Nagefire** [JuliaPluto/PlutoUI.jl#194]
As of version 0.17.7, Pluto supports dark mode but the widgets in PlutoUI don't match the color scheme. Are there plans to make PlutoUI dark mode compatible as well?

**Comment by pankgeorg** [comment]
> As of version 0.17.7, Pluto supports dark mode but the widgets in PlutoUI don't match the color scheme.

Which widgets do you refer to?

**Comment by Nagefire** [comment]
From what I've tested the table of contents, sliders, select boxes, and fields don't match the dark theme.

**Comment by pankgeorg** [comment]
I see plans for the table of contents in a pr https://github.com/JuliaPluto/PlutoUI.jl/pull/193, I don't know about the rest!

**Comment by fonsp** [comment]
Modern browsers will also render HTML5 inputs in dark mode, including Chrome and Safari, because we set https://developer.mozilla.org/en-US/docs/Web/CSS/color-scheme . What browser and version do you have? Can you try updating?

**Comment by fonsp** [comment]
https://web.dev/color-scheme/#demo

**Comment by fonsp** [comment]
But for the table of contents, thank you for opening the issue! We were able to fix this in #193 .

I also added a dark mode for Scrubbable and Clock, so I think we can close this issue now!
