### ISSUE TITLE
Name issues with other popular packages

### ISSUE THREAD

**Issue by dorn-gerhard** [JuliaPluto/PlutoUI.jl#195]
I just wanted to create a list with name conflicts with other popular Julia packages, 
maybe one could help users with a hint or warning messages ("use PlutoUI.### instead of ### to prevent name conflict"), if two packages with conflicting names were used.

One of such name conflicts is **Slider** with the **GLMakie.jl** package:
https://makie.juliaplots.org/stable/examples/layoutables/slider/index.html

**Comment by fonsp** [comment]
Also #166 !

**Comment by fonsp** [comment]
Now that https://github.com/fonsp/Pluto.jl/issues/890 is fixed, this is not an issue anymore :)
