### ISSUE TITLE
with_terminal broken

### ISSUE THREAD

**Issue by ilyagr** [JuliaPluto/PlutoUI.jl#196]
I think https://github.com/JuliaPluto/PlutoUI.jl/pull/140 broke `with_terminal` for me. As far as I can tell, the problem is that https://github.com/JuliaPluto/PlutoUI.jl/blob/9948cb4f30cfabb3f98f376a84395d57ff256004/src/TerminalNotebook.jl#L112-L113 needs to say something like

```js
ansi_up = new AnsiUp;
container.innerHTML = ansi_up.ansi_to_html(txt);
```

## Problem description

I saw this on Chrome 97 via Binder, so I couldn't test the fix. Here is what I saw.

![After](https://user-images.githubusercontent.com/4123047/151273386-936eb07f-80ed-4dee-8efe-c5b46f3eb99b.png)

(The behavior on latest version of `PlutoUI` is the same as in the screenshot)

On previous version of `PlutoUI`, it works.

![Before](https://user-images.githubusercontent.com/4123047/151273071-2b34f03a-d327-4ae6-9650-218b52af76ee.png)

**Comment by dralletje** [comment]
Huh, strange.. But good catch!

Can you try it out and make a pull request? :)

**Comment by ilyagr** [comment]
It might take me quite a while to get around to that, unfortunately.

**Comment by dojt** [comment]
`with_terminal()` has stopped working entirely for me: I cannot bring it to produce _any_ output.

![image](https://user-images.githubusercontent.com/57910358/151996391-37e064e3-09ce-4574-b4fc-413700e05126.png)

**Comment by icweaver** [comment]
Hey @dojt! Could you give a little bit more info about your setup? fwiw, I have been finding the following on my end at least:

Linux x86_64
Julia 1.7.1
Pluto main: https://github.com/fonsp/Pluto.jl/commit/143cae813478b18499b01dfa99e394fbdaef2dec
Pluto release: [v0.17.7](https://github.com/fonsp/Pluto.jl/releases/tag/v0.17.7)
PlutoUI main: https://github.com/JuliaPluto/PlutoUI.jl/commit/eb8b13ce97cbb92fe6e259d4169afbe657a82e0a
PlutoUI release: [v0.7.32](https://github.com/JuliaPluto/PlutoUI.jl/releases/tag/v0.7.32)

| Pluto // PlutoUI | main | release 
|:--------------:|:----:|:-------:|
|      main      |   ✅  |    ✅    |
|     release    |   ❌  |    ❌    |

So I would test again on the main branch of Pluto if you haven't tried it out already!

**Comment by dralletje** [comment]
Can you guys try this from main branch? Should be fixed now

**Comment by ilyagr** [comment]
I checked on binder.plutojl.org, and it works! (For now, one must remember to explicitly update PlutoUI to latest version). Thank you :) 

One thing that still bothers me a little is that if the `AnsiUp` fails to load for any reason (e.g. the user has no internet connection), `with_terminal` will stop working entirely; there is no graceful degradation or even notification to the user that something is wrong. Hopefully, that happens rarely.

**Comment by dralletje** [comment]
Yeah.. Next step is just embedding ansiUp in the notebook

**Comment by fonsp** [comment]
> One thing that still bothers me a little is that if the AnsiUp fails to load for any reason (e.g. the user has no internet connection), with_terminal will stop working entirely; there is no graceful degradation or even notification to the user that something is wrong. Hopefully, that happens rarely.

This is also fixed now!
