### ISSUE TITLE
Suggestion to remove `LocalResource` warning

### ISSUE THREAD

**Issue by mossr** [JuliaPluto/PlutoUI.jl#197]
Since the [recent changes to Pluto v0.17.6](https://discourse.julialang.org/t/ann-pluto-0-17-6/75011) allow for `@warn` to show up in the cell, I think the warning that comes with using `LocalResouce` should be removed as it is only useful for first-timers or beginners (I think the tip is valuable, but unnecessary to include in the notebook when this information is somewhat "obvious").

Here's an example of how the warning adds noise to a notebook:
![image](https://user-images.githubusercontent.com/1592413/151875429-5569160d-971c-4748-abe6-dc7dce79b122.png)

Just my opinion, but would love to discuss this.

**Comment by fonsp** [comment]
Removed in PlutoUI 0.7.35, releasing soon :)
