### ISSUE TITLE
Change TOC css to support dark theme

### ISSUE THREAD

**Issue by DhruvaSambrani** [JuliaPluto/PlutoUI.jl#205]
Currently `TableOfContents` still follows the light theme, but changes in css with the correct theme media queries should fix it. I do not mind doing this, but would like to know the procedure to decide on the exact colors?

Tagging @20akshay00

**Comment by fonsp** [comment]
This has already been fixed! https://github.com/JuliaPluto/PlutoUI.jl/pull/193 Be sure to update PlutoUI, see https://github.com/fonsp/Pluto.jl/wiki/%F0%9F%8E%81-Package-management
