### ISSUE TITLE
Interest in an equivalent of `@test`?

### ISSUE THREAD

**Issue by eahenle** [JuliaPluto/PlutoUI.jl#227]
I wrote a neat little macro, `@plutotest`, to help with test-driven development inside Pluto notebooks.  It functions essentially like the standard `@test` macro (so it can be copied into unit test scripts with only trivial editing) and provides a nice color-coded message box to indicate test passage/failure.  It's also designed to be useful when running the notebook as a standalone script.

If this is something others would find useful (I suspect so!) I will make a PR to add it.  I figured this would be the right package for it, but I'm open to suggestions as to alternatives.

**Comment by pankgeorg** [comment]
I think this repository is closer to pluto-specialized tests → https://github.com/JuliaPluto/PlutoTest.jl - feel free to open a PR there!

**Comment by eahenle** [comment]
@pankgeorg oh, nice.  They basically have what I do, but with extra features.  And here I thought I was so clever, haha!

**Comment by pankgeorg** [comment]
> They basically have what I do, but with extra features.
I'm glad you like it!

> And here I thought I was so clever, haha!

Well, you did write something that other people already think is useful enough to build, that sounds pretty clever to me!
Why don't you stick around here and there and maybe try to contribute novel features if you have some time? We are be excited to see what you'll build!! And it's not that any of this is bug free; small contributions make a difference too! Let's stay in touch!

Thanks for reaching out 🎉
