### ISSUE TITLE
Add cells that evaluate to docstrings to ToC

### ISSUE THREAD

**Issue by jerlich** [JuliaPluto/PlutoUI.jl#229]
This is similar to #116.

Currently, i have use a style where i have cells like
```
function doit(x)
...
end; md"#### doit - a function that does it"
```
so that my cell ends up in the ToC so i can jump to it easily.

But i think i would prefer to just have a docstring and have an option that cells with docstrings added to the Table of Contents.

It is possible to add this as an option?

**Comment by fonsp** [comment]
Hey @jerlich !

This feature got added recently, take a look at #226

Use it with 
```julia
TableOfContents(include_definitions=true)
```
