### ISSUE TITLE
support for LaTeX in `TableOfContents()`

### ISSUE THREAD

**Issue by SimonEnsemble** [JuliaPluto/PlutoUI.jl#235]
(feature request)

e.g. [here](https://simonensemble.github.io/pluto_nbs/graph_diffusion_blog.jl.html)

![image](https://user-images.githubusercontent.com/30643894/197612517-20e63da0-220f-492d-9d0a-9fc8630f7ba1.png)

**Comment by fonsp** [comment]
Implemented by https://github.com/JuliaPluto/PlutoUI.jl/pull/226 , update PlutoUI to get it!
