### ISSUE TITLE
End html input elements with "/>" 

### ISSUE THREAD

**Issue by schlichtanders** [JuliaPluto/PlutoUI.jl#276]
I am currently in the process of supporting other languages on Pluto. A lot works. One thing which does not yet work well is the use of PlutoUI as part of Markdown.

- I am already using `CommonMark` instead of the standard `Markdown`, because it supports html txt inside. This enables interpolation of complex html components into markdown table summaries for instance.
- while e.g. `PlutoUI.Select` works seamlessly, I realized that `PlutoUI.Slider` html is not correctly parsed by CommonMark.

The reason is that Slider and others use html `<input ...>` unclosed tags. 

Hence a simple fix to make the PlutoUI.Slider html work inside CommonMark is to close all those tags. Would this be possible?

**Comment by schlichtanders** [comment]
my excuses, I was wrong - it is the empty line inside the html string

**Comment by fonsp** [comment]
Yep! That's tricky, feel free to make a PR to PlutoUI to make components render to a one-line HTML.

You might also need to use MarkdownLiteral instead of CommonMark for the same reason as https://github.com/JuliaPluto/PlutoUI.jl/issues/274#issuecomment-1788855285 , but maybe it's supported in CommonMark also...

**Comment by fonsp** [comment]
This might be relevant https://github.com/JuliaPluto/PlutoUI.jl/pull/172

**Comment by schlichtanders** [comment]
Thank you for your help. I am now manually reformatting everything into a single line, however CommonMark still has problems dealing with this within Markdown Table syntax. Even pandoc cannot deal with html inside markdown tables, which is probably the reason why many Markdown implementations fall short here.

I am currently in the process of fixing it. See https://github.com/MichaelHatherly/CommonMark.jl/issues/66
