### ISSUE TITLE
Notebooks no longer run with Binder

### ISSUE THREAD

**Issue by kmarray98** [JuliaPluto/PlutoUI.jl#282]
PlutoUI no longer appears to run with Binder (I think since the update to the most recent Julia version). For example, when you run the example notebook at https://featured.plutojl.org/basic/plutoui.jl the notebook does not run, and gets stuck at the first step of initialising Binder. This seems to have broken every interactive Julia website built with Pluto using PlutoUI and Binder.

**Comment by pankgeorg** [comment]
I just got an instance from OVH; Binder's Quality of Service is deteriorating, but not much we can do about it :(

Closing as not actionable for PlutoUI
