### ISSUE TITLE
[Feature Request] Range or multi-handle Slider

### ISSUE THREAD

**Issue by briochemc** [JuliaPluto/PlutoUI.jl#34]
Would it be possible to have "range" sliders that bind two values (or a tuple?) and looks like

<img width=40% src="https://i0.wp.com/www.cssscript.com/wp-content/uploads/2016/06/multirange.png?fit=474%2C351&ssl=1">

PS: I thought I saw this issue before but could not find it again. Please close if this is a duplicate.

**Comment by icweaver** [comment]
Closed by #4?

**Comment by fonsp** [comment]
Yep!
