### ISSUE TITLE
Mismatch when default is out of range

### ISSUE THREAD

**Issue by RomansWorks** [JuliaPluto/PlutoUI.jl#58]
Hi, small issue which confused me for a while, is that the value shown might not match the value of the bound variable. 

Here's a basic reproduction in Pluto.jl:
```
begin
	using Pkg
	Pkg.activate(mktempdir())
end
```
```
begin
	Pkg.add(["PlutoUI",])
	using PlutoUI
end
```
```
@bind someval Slider(0.01:0.001:1, default=0.002, show_value=true)
```
Note that someval now shows 0.002 near the Slider. Also note that 0.002 is outside of the provided slider range.
```
someval
```
Note that someval is actual equal to 0.01 (i.e. it really is clamped to the slider range).

Thanks, 

Roman

**Comment by fonsp** [comment]
Thanks!

To fix this, we should round the default value to the nearest possible value, we should **not** error when the default value is illegal because of floating point trickiness

**Comment by fonsp** [comment]
Fixed!
