### ISSUE TITLE
Slider assigns wrong values if given a range of Unitful values?

### ISSUE THREAD

**Issue by schneiderfelipe** [JuliaPluto/PlutoUI.jl#74]
Hi, I think I found a bug regarding the use of PlutoUI.jl together with [Unitful.jl](https://github.com/PainterQubits/Unitful.jl). Basically, `Slider` changes some values unexpectedly when given Unitful ranges.

A working example would be:

```julia
begin
    using Unitful
    @bind T Slider((1000:6000)u"K", show_value=true)
end
```

![Captura de tela de 2021-02-09 17-06-05](https://user-images.githubusercontent.com/37125/107421859-414e8d00-6af9-11eb-88cf-8dd0811a6266.png)

**Comment by fonsp** [comment]
Hey! The solution to this would be #3, in the meantime you need to add a second cell:

```
T_withunit = T * u"K"
```
