### ISSUE TITLE
TableOfContents with aside=true doesn't play well with new html export layout

### ISSUE THREAD

**Issue by DhruvaSambrani** [JuliaPluto/PlutoUI.jl#97]
On html export, layout is centered, and floating ToC obscures the cells.

`body` should be set to `align-start` if ToC is floating.

**Comment by mossr** [comment]
+1 the ToC obstructs the notebook and does not follow when scrolling. Here's a GIF to put some fire under this issue 🔥
![ToC-static-bug](https://user-images.githubusercontent.com/1592413/133948205-e47906c8-acc4-4b13-a43a-c8130c9c2300.gif)

**Comment by fonsp** [comment]
@mossr In your case, the ToC is not scrolling because you are using https://htmlview.glitch.me/ , I will look into that later!
